name: Build and Publish Application Record

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - '*'

env:
  CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
  CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}
  CERC_REGISTRY_REST_ENDPOINT: ${{ secrets.CERC_REGISTRY_REST_ENDPOINT }}
  CERC_REGISTRY_GQL_ENDPOINT: ${{ secrets.CERC_REGISTRY_GQL_ENDPOINT }}
  CERC_REGISTRY_CHAIN_ID: ${{ secrets.CERC_REGISTRY_CHAIN_ID }}
  CERC_REGISTRY_APP_CRN: ${{ secrets.CERC_REGISTRY_APP_CRN }}
  CERC_REGISTRY_DEPLOYMENT_SHORT_HOSTNAME: ${{ secrets.CERC_REGISTRY_DEPLOYMENT_SHORT_HOSTNAME }}
  CERC_REGISTRY_DEPLOYMENT_CRN: ${{ secrets.CERC_REGISTRY_DEPLOYMENT_CRN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CI: false

      - name: Install Yarn and TypeScript
        run: |
          npm install -g yarn typescript

      - name: Setup registry CLI
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
          laconic --version

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Validate environment
        run: |
          echo "Validating environment variables..."
          [[ -z "$CERC_REGISTRY_USER_KEY" ]] && echo "CERC_REGISTRY_USER_KEY is not set" && exit 1
          [[ -z "$CERC_REGISTRY_BOND_ID" ]] && echo "CERC_REGISTRY_BOND_ID is not set" && exit 1
          echo "Environment validation completed successfully."

      - name: Prepare and run publish script
        run: |
          chmod +x scripts/publish-app-record.sh
          ./scripts/publish-app-record.sh